we should set xmlns:content for empty manifest
since we're now traversing such empty documents with:
'//content:text[@i18n-id]' XPaths, which otherwise cause

   Nokogiri::XML::XPath::SyntaxError:
     ERROR: Undefined namespace prefix: //content:text[@i18n-id]